version: "3.3"
services:
  php:
    build: './docker/php/'
    container_name: php_accomodation
    networks:
      - backend
      - frontend
    volumes:
      - ./src/:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    links:
      - mysql
  apache:
    build: './docker/apache/'
    container_name: apache_accomodation
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
    links:
      - mysql
  mysql:
    container_name: mariadb_accomodation
    image: mariadb:latest
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      # - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=accomodation
      - MYSQL_ROOT_PASSWORD=rootpassword
    command:
      ['--memlock=2M', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max-allowed-packet=128M']
  phpmyadmin:
    container_name: phpmyadmin_accomodation
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    networks:
      - backend
      - frontend
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
      - UPLOAD_LIMIT=300M
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
networks:
  frontend:
  backend: